"""FHIR R4 Bundle writer for synthetic episodes.

The bundle for each episode contains:
  * one Patient
  * one Observation per non-null lab/vital (LOINC-coded)
  * one Condition per active comorbidity flag (SNOMED-coded)
  * extra resources emitted by Synthea-style modules in src/syntha/modules/
    (Encounters, MedicationRequests, Procedures, CarePlans)
"""
from __future__ import annotations

import hashlib
import json
import uuid
from pathlib import Path

import numpy as np
import pandas as pd

from ..locale.turkish import (
    CONDITION_DISPLAY_TR,
    sample_address,
    sample_name,
)
from .codes import CONDITION_ICD10, CONDITION_SNOMED, GENDER_MAP, LAB_LOINC


def _is_present(v) -> bool:
    if v is None:
        return False
    try:
        return not bool(pd.isna(v))
    except (TypeError, ValueError):
        return True


def _patient_rng(row: pd.Series, patient_id: str) -> np.random.Generator:
    """Deterministic per-patient RNG so HumanName and Address are reproducible."""
    seed_src = f"{patient_id}|{row.get('HASTA_ID', '')}|{row.get('RF_EPISODE2', '')}"
    seed = int(hashlib.sha256(seed_src.encode("utf-8")).hexdigest()[:16], 16)
    return np.random.default_rng(seed)


def _patient_resource(row: pd.Series, patient_id: str) -> dict:
    age = int(row.get("age")) if _is_present(row.get("age")) else None
    is_male = (
        bool(int(row.get("gender_is_male", 0)))
        if _is_present(row.get("gender_is_male")) else False
    )
    gender = GENDER_MAP.get(int(is_male), "unknown")
    episode_dt = pd.to_datetime(row.get("episode_date"), errors="coerce")
    if pd.isna(episode_dt):
        episode_dt = pd.Timestamp.utcnow()
    birth = (episode_dt - pd.DateOffset(years=age)) if age is not None else None

    rng = _patient_rng(row, patient_id)
    given, family = sample_name(rng, is_male)
    addr = sample_address(rng)

    res = {
        "resourceType": "Patient",
        "id": patient_id,
        "gender": gender,
        "name": [{"use": "official", "family": family, "given": [given]}],
        "address": [{
            "use": "home",
            "type": "physical",
            "city": addr.city,
            "state": addr.state_code,
            "country": addr.country,
        }],
        "communication": [{
            "language": {
                "coding": [{
                    "system": "urn:ietf:bcp:47",
                    "code": "tr", "display": "Turkish",
                }],
                "text": "Turkish",
            },
            "preferred": True,
        }],
        "extension": [
            {
                "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
                "valueAddress": {"country": "TR"},
            }
        ],
        # The FHIR standard tag for synthetic/test resources, mandated by
        # Synthea and required by the medical-officer v0.5 review (G1):
        # every emitted patient carries an unambiguous "this is synthetic,
        # not a real human" marker so they can never be confused with real
        # patients if they leak into a downstream system.
        "meta": {
            "profile": ["http://hl7.org/fhir/StructureDefinition/Patient"],
            "tag": [{
                "system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
                "code": "HTEST",
                "display": "test health data (synthetic, not a real patient)",
            }, {
                "system": "https://github.com/Mmynemious/syntha/synthetic-source",
                "code": "syntha-copula",
                "display": "Generated by syntha — Gaussian-copula synthetic patient record generator",
            }],
        },
    }
    if birth is not None:
        res["birthDate"] = birth.strftime("%Y-%m-%d")
    return res


def _observation_resource(
    row: pd.Series, patient_id: str, column: str, effective_iso: str
) -> dict | None:
    value = row.get(column)
    if not _is_present(value):
        return None
    code, display, unit = LAB_LOINC[column]
    is_vital = column in {"bp_systolic", "bp_diastolic"}
    category = "vital-signs" if is_vital else "laboratory"
    return {
        "resourceType": "Observation",
        "id": str(uuid.uuid4()),
        "status": "final",
        "category": [
            {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                        "code": category,
                        "display": category.replace("-", " ").title(),
                    }
                ]
            }
        ],
        "code": {
            "coding": [
                {"system": "http://loinc.org", "code": code, "display": display}
            ],
            "text": display,
        },
        "subject": {"reference": f"urn:uuid:{patient_id}"},
        "effectiveDateTime": effective_iso,
        "valueQuantity": {
            "value": float(value),
            "unit": unit,
            "system": "http://unitsofmeasure.org",
            "code": unit,
        },
    }


def _condition_resource(patient_id: str, column: str, onset_iso: str) -> dict:
    sct_code, sct_display = CONDITION_SNOMED[column]
    icd_code, icd_display = CONDITION_ICD10.get(column, ("", ""))
    tr_display = CONDITION_DISPLAY_TR.get(column, sct_display)
    coding = [
        {"system": "http://snomed.info/sct", "code": sct_code, "display": sct_display},
    ]
    if icd_code:
        coding.append({
            "system": "http://hl7.org/fhir/sid/icd-10",
            "code": icd_code, "display": icd_display,
        })
    return {
        "resourceType": "Condition",
        "id": str(uuid.uuid4()),
        "clinicalStatus": {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
                    "code": "active",
                }
            ]
        },
        "verificationStatus": {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
                    "code": "confirmed",
                }
            ]
        },
        "code": {
            "coding": coding,
            "text": f"{sct_display} / {tr_display}",
        },
        "subject": {"reference": f"urn:uuid:{patient_id}"},
        "onsetDateTime": onset_iso,
    }


def _wrap_entries(resources: list[dict]) -> list[dict]:
    return [
        {
            "fullUrl": f"urn:uuid:{r['id']}",
            "resource": r,
            "request": {"method": "POST", "url": r["resourceType"]},
        }
        for r in resources
    ]


def episode_to_bundle(
    row: pd.Series,
    run_modules: bool = True,
    *,
    include_lab_history: bool = False,
) -> dict:
    """Build one transaction Bundle for a single synthetic episode."""
    patient_id = str(uuid.uuid4())
    episode_dt = pd.to_datetime(row.get("episode_date"), errors="coerce")
    if pd.isna(episode_dt):
        episode_dt = pd.Timestamp.utcnow()
    effective_iso = episode_dt.strftime("%Y-%m-%dT%H:%M:%SZ")

    resources: list[dict] = [_patient_resource(row, patient_id)]

    for col in LAB_LOINC:
        if col in row.index:
            obs = _observation_resource(row, patient_id, col, effective_iso)
            if obs is not None:
                resources.append(obs)

    condition_ids: dict[str, str] = {}
    for col in CONDITION_SNOMED:
        if col in row.index and _is_present(row.get(col)) and int(row.get(col)) == 1:
            cond = _condition_resource(patient_id, col, effective_iso)
            resources.append(cond)
            condition_ids[col] = cond["id"]

    if run_modules:
        # Lazy import avoids a circular dependency at package init time.
        from ..modules import REGISTRY
        from ..modules.base import ModuleContext

        ctx = ModuleContext(
            patient_id=patient_id, episode_iso=effective_iso,
            condition_ids=condition_ids,
        )
        for module in REGISTRY:
            if module.applies(row):
                resources.extend(module.expand(row, ctx).resources)

    # v0.5.4: group constituent Observations into DiagnosticReport resources
    # so downstream FHIR consumers see ordered-together labs as panels.
    from .panels import diagnostic_reports_for
    panel_reports = diagnostic_reports_for(
        resources, patient_id, effective_iso, LAB_LOINC,
    )
    resources.extend(panel_reports)

    # v0.5: clinical-realism extras — Charlson CCI as RiskAssessment, PHQ-9
    # for depression-flagged patients, GAD-7 for anxiety-flagged, and
    # FamilyMemberHistory for family-risk flags.
    if run_modules:
        from .clinical_extras import (
            charlson_risk_assessment,
            family_history_resources,
            gad7_observation,
            phq9_observation,
        )

        rng_extras = _patient_rng(row, patient_id)

        cci = row.get("charlson_cci") if "charlson_cci" in row.index else None
        if cci is not None and not pd.isna(cci):
            ra = charlson_risk_assessment(patient_id, float(cci), effective_iso)
            if ra:
                resources.append(ra)

        if "Depresyon" in row.index and not pd.isna(row.get("Depresyon")):
            obs = phq9_observation(
                patient_id, int(row.get("Depresyon")),
                effective_iso, rng_extras,
            )
            if obs is not None:
                resources.append(obs)

        if "Anksiyete" in row.index and not pd.isna(row.get("Anksiyete")):
            obs = gad7_observation(
                patient_id, int(row.get("Anksiyete")),
                effective_iso, rng_extras,
            )
            if obs is not None:
                resources.append(obs)

        resources.extend(family_history_resources(patient_id, row, effective_iso))

    return {
        "resourceType": "Bundle",
        "id": str(uuid.uuid4()),
        "type": "transaction",
        "timestamp": effective_iso,
        "entry": _wrap_entries(resources),
    }


def write_fhir_bundles(
    df: pd.DataFrame,
    out_dir: str | Path,
    fmt: str = "ndjson",
    run_modules: bool = True,
    *,
    include_lab_history: bool = False,
) -> Path:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    if fmt == "ndjson":
        target = out / "bundles.ndjson"
        with open(target, "w", encoding="utf-8") as f:
            for _, row in df.iterrows():
                bundle = episode_to_bundle(
                    row, run_modules, include_lab_history=include_lab_history,
                )
                f.write(json.dumps(bundle, ensure_ascii=False))
                f.write("\n")
        return target
    bundles_dir = out / "bundles"
    bundles_dir.mkdir(parents=True, exist_ok=True)
    for i, (_, row) in enumerate(df.iterrows()):
        bundle = episode_to_bundle(
            row, run_modules, include_lab_history=include_lab_history,
        )
        with open(bundles_dir / f"patient_{i:06d}.json", "w", encoding="utf-8") as f:
            json.dump(bundle, f, ensure_ascii=False, indent=2)
    return bundles_dir
